### ISSUE TITLE
Scripts missing / not recognised in project

### ISSUE THREAD

**Issue by SimonDarksideJ** [Microsoft/InsiderDevTour18-MR#2]
I've taken a fresh clone of the project this week for testing and I'm hitting multiple issues.

The first relates to the Scripts used on Prefabs, either not being recognised or reporting errors.

For example, the Room prefab.  When I select it in either the Project view or in any of the scenes, it reports the attached script is missing / invalid or has build errors (As shown below).  However, there are no build errors in the scene.

![image](https://user-images.githubusercontent.com/1793042/40920429-67ec979a-6804-11e8-8e58-07b75fd4a205.png)

P.S.
The instructions on the front screen state the wrong location for the Room prefab

It currently states
``` 3D Models/Prefabs folder, drag the RoomPrefab```

But the actual location is
```/Prefabs folder, drag the RoomPrefab``` (root folder)

**Comment by ericahlstrom** [comment]
Fixed the prefab and instructions. Thanks.
